# We don't care about the language here, except that setting
# language: cpp will override our CC and CXX env variables below
# and we do not want that !
language: Ruby

dist: trusty
sudo: required

addons:
  apt:
    packages:
      - python3-pip

matrix:
    include:
    ##############
    # GCC
    ##############
    - os: linux
      compiler: gcc
      env: GCC_VERSION=8
        - CC=gcc-8
        - CXX=g++-8
        - CXX_STANDARD=14
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8']
    - os: linux
      compiler: gcc
      env: GCC_VERSION=8
        - CC=gcc-8
        - CXX=g++-8
        - CXX_STANDARD=17
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8']
    - os: linux
      compiler: gcc
      env: GCC_VERSION=7
        - CC=gcc-7
        - CXX=g++-7
        - CXX_STANDARD=14
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
    - os: linux
      compiler: gcc
      env: GCC_VERSION=7
        - CC=gcc-7
        - CXX=g++-7
        - CXX_STANDARD=17
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
    - os: linux
      compiler: gcc
      env: GCC_VERSION=6
        - CC=gcc-6
        - CXX=g++-6
        - CXX_STANDARD=14
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
    - os: linux
      compiler: gcc
      env: GCC_VERSION=5
        - CC=gcc-5
        - CXX=g++-5
        - CXX_STANDARD=14
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']

    ##############
    # CLANG
    ##############
    - os: linux
      compiler: clang
      env: CLANG_VERSION=7
        - CC=clang-7
        - CXX=clang++-7
        - CXX_STANDARD=14
      addons:
        apt:
          sources: ['llvm-toolchain-trusty', 'llvm-toolchain-trusty-7', 'ubuntu-toolchain-r-test']
          packages: ['clang-7', 'libc++-7-dev', 'libc++abi-7-dev']
    - os: linux
      compiler: clang
      env: CLANG_VERSION=6.0
        - CC=clang-6.0
        - CXX=clang++-6.0
        - CXX_STANDARD=14
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
          packages: ['clang-6.0', 'g++-6']
    - os: linux
      compiler: clang
      env: CLANG_VERSION=7
        - CC=clang-7
        - CXX=clang++-7
        - CXX_STANDARD=17
      addons:
        apt:
          sources: ['llvm-toolchain-trusty', 'llvm-toolchain-trusty-7', 'ubuntu-toolchain-r-test']
          packages: ['clang-7', 'libc++-7-dev', 'libc++abi-7-dev']

    ##############
    # OSX / APPLECLANG
    ##############
    - os: osx
      osx_image: xcode10
      env:
        - CXX=clang
        - OSX=1
        - CXX_STANDARD=17
    - os: osx
      osx_image: xcode10
      env:
        - CXX=clang
        - OSX=1
        - CXX_STANDARD=14
    - os: osx
      osx_image: xcode9.4
      env:
        - CXX=clang
        - OSX=1
        - CXX_STANDARD=14


before_install:
  - echo "Before install"
  - |
    git submodule init
    git submodule update
  - |
    if [ "${CLANG_VERSION}" == "7" ]; then
      export CXXFLAGS="-stdlib=libc++"
    fi

install:
  - mkdir -p build

script:
  - which $CXX
  - $CXX --version
